/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalRevenueNPR' : bigint,
  'ordersByStatus' : Array<[OrderStatus, bigint]>,
  'totalOrders' : bigint,
}
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export type DeliveryZone = { 'terai' : null } |
  { 'hilly' : null } |
  { 'kathmanduValley' : null } |
  { 'mountain' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'trackingCode' : [] | [string],
  'deliveryAddress' : string,
  'shippingCostNPR' : bigint,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'createdAt' : bigint,
  'deliveryZone' : DeliveryZone,
  'totalNPR' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'priceNPR' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'cashOnDelivery' : null } |
  { 'card' : null } |
  { 'esewa' : null } |
  { 'khalti' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : ProductCategory,
  'priceNPR' : bigint,
}
export type ProductCategory = { 'eco' : null } |
  { 'herbal' : null } |
  { 'sustainable' : null };
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : ProductCategory,
  'priceNPR' : bigint,
}
export interface Review {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
}
export interface TrashReport {
  'id' : bigint,
  'status' : TrashReportStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'imageUrl' : string,
  'location' : string,
}
export type TrashReportStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rewarded' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem { 'productId' : ProductId, 'addedAt' : bigint }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'addReview' : ActorMethod<[ProductId, bigint, string], bigint>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardEcoPoints' : ActorMethod<[Principal, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllCustomers' : ActorMethod<[], Array<Principal>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTrashReports' : ActorMethod<[], Array<TrashReport>>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDeliveryZones' : ActorMethod<[], Array<[string, bigint]>>,
  'getMyEcoPoints' : ActorMethod<[], bigint>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyTrashReports' : ActorMethod<[], Array<TrashReport>>,
  'getMyWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<[string, bigint]>>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getReviewsForProduct' : ActorMethod<[ProductId], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[PaymentMethod, string, DeliveryZone], bigint>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'submitTrashReport' : ActorMethod<[string, string], bigint>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'toggleProductActive' : ActorMethod<[ProductId, boolean], undefined>,
  'updateCartItemQuantity' : ActorMethod<[ProductId, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateOrderTracking' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], undefined>,
  'changeAdminPassword' : ActorMethod<[string], undefined>,
  'claimAdminWithPassword' : ActorMethod<[string], boolean>,
  'verifyTrashReport' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];