/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'eco' : IDL.Null,
  'herbal' : IDL.Null,
  'sustainable' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'priceNPR' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'priceNPR' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
  'esewa' : IDL.Null,
  'khalti' : IDL.Null,
});
export const DeliveryZone = IDL.Variant({
  'terai' : IDL.Null,
  'hilly' : IDL.Null,
  'kathmanduValley' : IDL.Null,
  'mountain' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceNPR' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'trackingCode' : IDL.Opt(IDL.Text),
  'deliveryAddress' : IDL.Text,
  'shippingCostNPR' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'deliveryZone' : DeliveryZone,
  'totalNPR' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const TrashReportStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rewarded' : IDL.Null,
});
export const TrashReport = IDL.Record({
  'id' : IDL.Nat,
  'status' : TrashReportStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const Analytics = IDL.Record({
  'totalRevenueNPR' : IDL.Nat,
  'ordersByStatus' : IDL.Vec(IDL.Tuple(OrderStatus, IDL.Nat)),
  'totalOrders' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const WishlistItem = IDL.Record({
  'productId' : ProductId,
  'addedAt' : IDL.Int,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
  'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardEcoPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllTrashReports' : IDL.Func([], [IDL.Vec(TrashReport)], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getDeliveryZones' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getMyEcoPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyTrashReports' : IDL.Func([], [IDL.Vec(TrashReport)], ['query']),
  'getMyWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
  'getNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getReviewsForProduct' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [PaymentMethod, IDL.Text, DeliveryZone],
      [IDL.Nat],
      [],
    ),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitTrashReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'toggleProductActive' : IDL.Func([ProductId, IDL.Bool], [], []),
  'updateCartItemQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateOrderTracking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
  'verifyTrashReport' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'eco' : IDL.Null,
    'herbal' : IDL.Null,
    'sustainable' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'priceNPR' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'priceNPR' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
    'esewa' : IDL.Null,
    'khalti' : IDL.Null,
  });
  const DeliveryZone = IDL.Variant({
    'terai' : IDL.Null,
    'hilly' : IDL.Null,
    'kathmanduValley' : IDL.Null,
    'mountain' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceNPR' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'trackingCode' : IDL.Opt(IDL.Text),
    'deliveryAddress' : IDL.Text,
    'shippingCostNPR' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'deliveryZone' : DeliveryZone,
    'totalNPR' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const TrashReportStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rewarded' : IDL.Null,
  });
  const TrashReport = IDL.Record({
    'id' : IDL.Nat,
    'status' : TrashReportStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const Analytics = IDL.Record({
    'totalRevenueNPR' : IDL.Nat,
    'ordersByStatus' : IDL.Vec(IDL.Tuple(OrderStatus, IDL.Nat)),
    'totalOrders' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const WishlistItem = IDL.Record({
    'productId' : ProductId,
    'addedAt' : IDL.Int,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
    'addReview' : IDL.Func([ProductId, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardEcoPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllTrashReports' : IDL.Func([], [IDL.Vec(TrashReport)], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getDeliveryZones' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getMyEcoPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyTrashReports' : IDL.Func([], [IDL.Vec(TrashReport)], ['query']),
    'getMyWishlist' : IDL.Func([], [IDL.Vec(WishlistItem)], ['query']),
    'getNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviewsForProduct' : IDL.Func(
        [ProductId],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [PaymentMethod, IDL.Text, DeliveryZone],
        [IDL.Nat],
        [],
      ),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitTrashReport' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'toggleProductActive' : IDL.Func([ProductId, IDL.Bool], [], []),
    'updateCartItemQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateOrderTracking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [], []),
    'verifyTrashReport' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };